Hoes
OmniacDev/Enderverse-Realm pull request #1
Opened 2024-11-08 08:37 UTC by SaiMonto

Added the hoes

2024-11-08 08:57 UTC, OmniacDev commented
Bump the manifest versions up to 1.0.10

2024-11-08 23:00 UTC, SaiMonto commented
version added

2024-11-08 23:17 UTC, OmniacDev requested changes

2024-11-09 23:30 UTC, OmniacDev requested changes
Rename these files

2024-11-09 23:30 UTC, OmniacDev commented on packs/RP/models/entity/attachable/geometry.enderverse_hoe.json
`ev_hoe.geometry.json`

2024-11-09 23:30 UTC, OmniacDev commented on packs/RP/animations/attachables/ameythst.animation.json
`ev_hoe.animation.json`

2024-11-10 01:59 UTC, OmniacDev approved these changes
LGTM

2024-11-10 01:59 UTC, merged